name: 'Install linuxdeploy'
description: 'Install Linuxdeploy on your Github Actions workflows with just one simple action'
author: 'miurahr'
branding:
  icon: 'package'
  color: 'green'
inputs:
  dir:
    description: 'Directory to install'
  plugins:
    description: 'Plugin modules to install'
runs:
  using: 'node16'
  main: 'dist/index.js'
